// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFv8mLSVw2Gha654QHIG5mfuOKSp9WQQ',
    appId: '1:145036666215:web:43fc90df631edd66febbc2',
    messagingSenderId: '145036666215',
    projectId: 'storeapp-77c7c',
    authDomain: 'storeapp-77c7c.firebaseapp.com',
    databaseURL: 'https://storeapp-77c7c-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-77c7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2g_i-xa-Me118cmi_JSVna35Virc0AGI',
    appId: '1:145036666215:android:01d079bf40eaa191febbc2',
    messagingSenderId: '145036666215',
    projectId: 'storeapp-77c7c',
    databaseURL: 'https://storeapp-77c7c-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-77c7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_60cs-2uty7TH2dlCguSsUrs6aHrm2jc',
    appId: '1:145036666215:ios:d8cc8dc2e7d5b2eafebbc2',
    messagingSenderId: '145036666215',
    projectId: 'storeapp-77c7c',
    databaseURL: 'https://storeapp-77c7c-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-77c7c.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.dine.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_60cs-2uty7TH2dlCguSsUrs6aHrm2jc',
    appId: '1:145036666215:ios:d8cc8dc2e7d5b2eafebbc2',
    messagingSenderId: '145036666215',
    projectId: 'storeapp-77c7c',
    databaseURL: 'https://storeapp-77c7c-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-77c7c.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.dine.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYFv8mLSVw2Gha654QHIG5mfuOKSp9WQQ',
    appId: '1:145036666215:web:7ba6279587fbe29cfebbc2',
    messagingSenderId: '145036666215',
    projectId: 'storeapp-77c7c',
    authDomain: 'storeapp-77c7c.firebaseapp.com',
    databaseURL: 'https://storeapp-77c7c-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-77c7c.firebasestorage.app',
  );
}